apiVersion: v1
kind: Secret
metadata:
  name: kms-plugin-config
  namespace: openshift-config
type: Opaque
stringData:
  config.yaml: |
    kind: VaultConfig
    apiVersion: apiserver.config.k8s.io/v1
    vault:
      address: "http://vault.vault.svc.cluster.local:8200"
      transitKeyName: "kubernetes-encryption"
      auth:
        type: "approle"
        approle:
          roleID: "50e11260-b920-6ea6-a929-0c410e34b4d8"
          secretID: "2ae4c3b7-c268-cc34-c367-bc69daae7e43"
