apiVersion: v1
kind: Secret
metadata:
  name: kms-plugin-config
  namespace: openshift-config
type: Opaque
stringData:
  config.yaml: |
    kind: VaultConfig
    apiVersion: apiserver.config.k8s.io/v1
    vault:
      address: "http://vault.vault.svc.cluster.local:8200"
      transitKeyName: "kubernetes-encryption"
      auth:
        type: "approle"
        approle:
          roleID: "577c005a-d039-693c-a896-47158ff796af"
          secretID: "69a4d9e3-ed31-440e-4a3f-7783ee78ea0b"
